apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepsequence-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deepsequence-api
  template:
    metadata:
      labels:
        app: deepsequence-api
    spec:
      containers:
      - name: api
        image: deepsequence-api:latest
        ports:
        - containerPort: 8000